#!/usr/bin/env sh
bun run lint-staged

changed_files="$(git diff --cached --name-only)"

if echo "$changed_files" | grep -Eq '\.langium$'; then
  bun run --cwd packages/language generate
fi
if echo "$changed_files" | grep -Eq '(src\/|test\/|\.langium$)'; then
  bun test --coverage
fi
if echo "$changed_files" | grep -Eq '^packages\/language\/'; then
  bun run --cwd packages/language build
fi
if echo "$changed_files" | grep -Eq '^packages\/docml\/'; then
  bun run --cwd packages/docml build
fi
if echo "$changed_files" | grep -Eq '^packages\/docs\/'; then
  bun run --cwd packages/docs build
fi
